from dataclasses import dataclass
from pxr import Usd, UsdGeom
from .constants import CONTROLLER_SUFFIX

# In this file we are just going to be making an inventory of all of the pedicels and leaves in the cluster for future reference

@dataclass
class PedicelData:
    prim: Usd.Prim
    hinge: tuple = None
    root: Usd.Prim = None

@dataclass
class LeafData:
    prim: Usd.Prim  # Will now store the top-level editable Xform (e.g., foliage_leaf_01)
    root: Usd.Prim = None

class PlantRegistry:
    """Discovers important plant components in the stage."""

    def __init__(self, stage):
        self.stage = stage
        self.pedicels = []  # [pedicel_1, pedicel_2....]
        self.leaves = []

    def build(self):
        """Populate the registry."""
        self.pedicels.clear()
        self.leaves.clear()

        for prim in self.stage.Traverse():
            if not prim.IsValid():
                continue

            name = prim.GetName()
            name_lower = name.lower()

            # Skip the rig prims that were generated by us
            if CONTROLLER_SUFFIX.lower() in name_lower:
                continue

            # Identify pedicels
            if name_lower.startswith("pedicel_"):
                self.pedicels.append(PedicelData(prim))

            # Identify top-level editable leaf Xforms
            # They must start with "foliage_leaf_" and be an Xform (not the nested "object_0" mesh, gonna be using the controller approach)
            elif name_lower.startswith("foliage_leaf_") and prim.IsA(UsdGeom.Xform):
                self.leaves.append(LeafData(prim))

        # Sort elements by name so we have deterministic order during randomizations
        self.pedicels.sort(key=lambda p: p.prim.GetName())
        self.leaves.sort(key=lambda l: l.prim.GetName())

    def summary(self):
        print("\n===== Plant Registry =====")
        print(f"Pedicels: {len(self.pedicels)}")
        print(f"Leaves:   {len(self.leaves)}")
        print("==========================")

